"""add expiration and password hash.

Revision ID: c73514d519df
Revises: 45c7c3141a21
Create Date: 2022-03-31 11:12:48.194213

"""

# revision identifiers, used by Alembic.
revision = 'c73514d519df'
down_revision = '45c7c3141a21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dial_account', sa.Column('expire_at', sa.DateTime(), nullable=True))
    op.add_column('dial_account', sa.Column('password_hash', sa.String(length=130), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dial_account', 'expire_at')
    op.drop_column('dial_account', 'password_hash')
    ### end Alembic commands ###
